### ISSUE TITLE
Bot crashes with "Bad Request: message thread not found" after deleting a topic

### ISSUE THREAD

**Issue by alexios-oss** [ruitunion-org/feedback-bot#1]
### Description

The bot crashes with an error when a message is sent after deleting a previously created topic.

### Repro steps

1. Write a message to the bot. The bot will create a topic in the chat if it does not exist yet.
2. Delete the topic.
3. Write a message again.

### Expected behavior

The application should create a new topic.

### Actual behavior

The application crashes with an error.

### Logs

```
feedback-bot_1  |       BackgroundService failed
feedback-bot_1  |       Telegram.Bot.Exceptions.ApiRequestException: Bad Request: message thread not found
feedback-bot_1  |          at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
feedback-bot_1  |          at Telegram.Bot.TelegramBotClientExtensions.ForwardMessageAsync(ITelegramBotClient botClient, ForwardMessageRequest request, CancellationToken cancellationToken)
```

**Comment by atilaalcantara** [comment]
excuse me sir, i was trying to set up the project, but setting up telegram does not show enable topics as admin, i tried creating a private channel and a private group, in channel it doesnt show, in group it says:
![image](https://github.com/user-attachments/assets/905002d3-dfb3-4473-aa84-531f618639ad)

**Comment by alexios-oss** [comment]
Hello @atilao4501,

I think you need to update your desktop client. [Topics should be available in all groups, regardless of size](https://telegram.org/blog/hidden-media-zero-storage-profile-pics?ln=r#topics-for-groups-of-any-size).

Next time, could you please create a new issue for your question, as it doesn't relate to the original bug.

Thank you.
