### ISSUE TITLE
Translation to a clean architecture (or another)

### ISSUE THREAD

**Issue by smellilac** [ruitunion-org/feedback-bot#7]
You don't have a "Discussion" section, so I'll propose my changes here.
There is no architecture at all in your project. If you agree, I will correct this.

**Comment by alexios-oss** [comment]
Hi @smellilac,

Our project is small (about 900 lines). During development we're focused on keeping everything simple. We don't think the project needs some specific architechture right now.

But, if you want to refactor and show us how it could be improved, feel free to do so. We will review the changes. But we can't promise to accept them.
